### ISSUE TITLE
Upgrade guide from v2 to v3

### ISSUE THREAD

**Issue by Lewiscowles1986** [ljharb/node-json-file#10]
Looking at mean-cli, it seems it uses an outdated version of this lib, and I am wondering if anyone has any tips or links, or a guide to upgrade v2 to v3

**Comment by ljharb** [comment]
As you can see in the [commit log](https://github.com/ljharb/node-json-file/compare/v2.0.1...v3.0.0) and the [changelog](https://github.com/ljharb/node-json-file/blob/master/CHANGELOG.md#300--2015-05-03), the only implementation change is 01f75226a6b9c2d409d9960530c2af2e2cc37942, which is also a breaking change.

Specifically, if there are any `fs.writeFile` errors, the promise will now be rejected instead of resolved. My expectation is that literally nobody is relying on the success code path for this case, but since it's possible, I considered it breaking.

You can very likely upgrade safely without concern.
